### ISSUE TITLE
Test FOODON and CDNO harvested materials

### ISSUE THREAD

**Issue by kaiiam** [kaiiam/DEMO#1]
xref https://github.com/Southern-Cross-Plant-Science/cdno/issues/4 

From @ddooley we have:

> 'plant part' and 'derives from' some Taxon is the minimal information required for describing the sample substance

> "apple subClassOf 'pome fruit' and derives from some "Malus pumila'"

I'm reading this to be the owl equivalence axiom: 

```
'PO term'
 and ('derives from' some 'NCBITaxon term')
```

@ddooley also mentions

> All this suggests that the natural home for these sample substances will be under FoodOn's "part of organism" > "plant structure" branch (a PO term), e.g. 'apple' will be under 'pome fruit'.

Stating that this module should be under the FOODON:[part of plant](http://purl.obolibrary.org/obo/FOODON_03420174), in which case to assert this we would need to go with something like the second axiom I'd proposed:

```
'part of plant'
 and ('composed primarily of' some 
    ('PO term'
     and ('derives from' some 'NCBITaxon term')))
```

**Comment by kaiiam** [comment]
In a branch for issue-1 here I'm going to try adding both of these design patterns as DOSDPs. calling them 1) plant_taxon and 2) part_plant_taxon respectively

**Comment by ddooley** [comment]
I'm simplifying some redundancy by replacing foodon "part of plant" with PO "plant structure" unless you folks have objections.  Under "plant structure" will be many PO terms per their branch, but some FoodOn groupings too.  So the new hierarchy looks like:

![image](https://user-images.githubusercontent.com/4000582/92256985-56a7f700-ee89-11ea-8c96-0c78b0b6f104.png)

So I'm a little uncertain about need for 'composed primarily of' ... but lets discuss.
